// CORE-007 — O6: useAutoSave hook.
// Triggers DraftSave on the Wails backend every 2s of inactivity (debounce).
// Errors are logged silently — auto-save must not distract the author.

import { useEffect, useRef } from 'react';
import type { StoryDraft } from '@/components/spdd/types';

/** Debounce delay in ms before triggering DraftSave. */
const AUTOSAVE_DELAY_MS = 2000;

/**
 * Automatically saves the current draft to the Go backend whenever it
 * changes, with a 2-second debounce to avoid hammering the disk.
 *
 * @param draft   The current draft from the Zustand store.
 * @param enabled Set to false to suspend auto-save (e.g. during export).
 */
export function useAutoSave(draft: StoryDraft, enabled: boolean): void {
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!enabled) return;

    // Cancel any pending save before scheduling a new one.
    if (timerRef.current !== null) {
      clearTimeout(timerRef.current);
    }

    timerRef.current = setTimeout(async () => {
      try {
        // window.go is the Wails runtime namespace.
        // The binding DraftSave is generated by `wails dev` / `wails build`
        // under wailsjs/go/main/App.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const go = (window as any).go;
        if (go?.main?.App?.DraftSave) {
          await go.main.App.DraftSave({
            id: draft.id,
            slug: draft.slug,
            title: draft.title,
            status: draft.status,
            created: draft.created,
            updated: draft.updated,
            owner: draft.owner,
            modules: [...draft.modules],
            sections: { ...draft.sections },
            ac: draft.ac.map((c) => ({ ...c })),
            savedAt: new Date().toISOString(),
          });
        }
      } catch (err) {
        // Silent: auto-save errors must not disrupt the editing flow.
        console.error('[useAutoSave] DraftSave failed:', err);
      }
    }, AUTOSAVE_DELAY_MS);

    return () => {
      if (timerRef.current !== null) {
        clearTimeout(timerRef.current);
      }
    };
  // Draft identity comparison: run the effect on every draft object change.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [draft, enabled]);
}
