// Package integration_test exercises the yukki workflow across multiple
// internal packages (workflow, provider, templates, artifacts) without
// invoking a real LLM CLI. The Provider is mocked; templates and artifacts
// touch the real file system in a t.TempDir.
package integration_test

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yukki-project/yukki/internal/artifacts"
	"github.com/yukki-project/yukki/internal/provider"
	"github.com/yukki-project/yukki/internal/templates"
	"github.com/yukki-project/yukki/internal/workflow"
)

const stubStoryMarkdown = `---
id: STORY-001
slug: integration
title: Integration Story
status: draft
created: 2026-04-30
updated: 2026-04-30
owner: TBD
modules:
  - cmd/yukki
---

# Integration Story

Generated by the integration test stub provider.

## Background

Cross-package integration test of the yukki story workflow.

## Acceptance Criteria

### AC1
- Given the workflow runs end to end with a mock provider
- When the user invokes ` + "`" + `RunStory` + "`" + `
- Then a valid frontmatter file lands on disk
`

func newWorkflowOptions(t *testing.T, mock *provider.MockProvider, projectDir, desc, prefix string) workflow.StoryOptions {
	t.Helper()
	return workflow.StoryOptions{
		Description:    desc,
		Prefix:         prefix,
		Provider:       mock,
		TemplateLoader: templates.NewLoader(projectDir),
		Writer:         artifacts.NewWriter(filepath.Join(projectDir, "stories")),
	}
}

func TestRunStory_EndToEnd_MockProvider(t *testing.T) {
	dir := t.TempDir()
	mock := &provider.MockProvider{Response: stubStoryMarkdown}

	opts := newWorkflowOptions(t, mock, dir, "describe my feature", "STORY")
	path, err := workflow.RunStory(context.Background(), opts)
	if err != nil {
		t.Fatalf("RunStory: %v", err)
	}

	expected := filepath.Join(dir, "stories", "STORY-001-integration-story.md")
	if path != expected {
		t.Fatalf("expected %s, got %s", expected, path)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read produced file: %v", err)
	}
	if !strings.Contains(string(got), "id: STORY-001") {
		t.Fatalf("frontmatter missing expected id, got\n%s", got)
	}

	// Single provider call recorded.
	if len(mock.Calls) != 1 {
		t.Fatalf("expected provider invoked once, got %d", len(mock.Calls))
	}
	// Prompt must mention the assigned id (so claude/the LLM can write it back).
	if !strings.Contains(mock.Calls[0], "STORY-001") {
		t.Fatal("expected the assigned id to be inlined in the prompt")
	}
}

func TestRunStory_NextIDIncrementsAcrossInvocations(t *testing.T) {
	dir := t.TempDir()
	mock := &provider.MockProvider{Response: stubStoryMarkdown}

	for i := 1; i <= 3; i++ {
		opts := newWorkflowOptions(t, mock, dir, "feature "+string(rune('A'+i-1)), "EXT")
		_, err := workflow.RunStory(context.Background(), opts)
		if err != nil {
			t.Fatalf("RunStory iteration %d: %v", i, err)
		}
	}

	entries, _ := os.ReadDir(filepath.Join(dir, "stories"))
	got := map[string]bool{}
	for _, e := range entries {
		got[e.Name()] = true
	}
	for _, want := range []string{
		"EXT-001-integration-story.md",
		"EXT-002-integration-story.md",
		"EXT-003-integration-story.md",
	} {
		if !got[want] {
			t.Errorf("expected file %s, missing", want)
		}
	}
}

func TestRunStory_StubError_NoFileWritten(t *testing.T) {
	dir := t.TempDir()
	mock := &provider.MockProvider{Err: provider.ErrGenerationFailed}

	opts := newWorkflowOptions(t, mock, dir, "desc", "STORY")
	_, err := workflow.RunStory(context.Background(), opts)
	if !errors.Is(err, provider.ErrGenerationFailed) {
		t.Fatalf("expected ErrGenerationFailed, got %v", err)
	}

	storiesDir := filepath.Join(dir, "stories")
	if entries, err := os.ReadDir(storiesDir); err == nil && len(entries) > 0 {
		t.Fatalf("expected no story files on provider failure, got %d", len(entries))
	}
}

func TestRunStory_TemplateOverrideTakesPrecedence(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "templates"), 0o755); err != nil {
		t.Fatal(err)
	}
	const projectMarker = "PROJECT-LEVEL TEMPLATE\n"
	if err := os.WriteFile(filepath.Join(dir, "templates", "story.md"), []byte(projectMarker), 0o644); err != nil {
		t.Fatal(err)
	}

	mock := &provider.MockProvider{Response: stubStoryMarkdown}
	opts := newWorkflowOptions(t, mock, dir, "desc", "STORY")
	_, err := workflow.RunStory(context.Background(), opts)
	if err != nil {
		t.Fatalf("RunStory: %v", err)
	}

	if len(mock.Calls) != 1 {
		t.Fatalf("expected one provider call, got %d", len(mock.Calls))
	}
	if !strings.Contains(mock.Calls[0], projectMarker) {
		t.Fatal("expected project-level template content to be embedded in the prompt")
	}
}
