// AV-WORKAROUND STUB — normally auto-generated by `wails generate module`.
// Hand-written locally because corporate Defender blocks the helper binary
// Wails builds in %TEMP% during binding generation. Cf. TICKET IT in TODO.md.
// Wails overwrites this file cleanly once the AV exclusion is in place.

// (Greet was removed in UI-001c per D-C11.)
export function SelectProject(): Promise<string>;
export function AllowedKinds(): Promise<string[]>;
export function ListArtifacts(kind: string): Promise<Meta[]>;
export function GetClaudeStatus(): Promise<ClaudeStatus>;
export function InitializeSPDD(dir: string): Promise<void>;
export function ReadArtifact(path: string): Promise<string>;

// UI-001c
export function RunStory(description: string, prefix: string, strictPrefix: boolean): Promise<string>;
export function AbortRunning(): Promise<void>;
export function SuggestedPrefixes(): Promise<string[]>;

// UI-008
export function UpdateArtifactStatus(path: string, newStatus: string): Promise<void>;
export function AllowedTransitions(currentStatus: string): Promise<string[]>;
export function UpdateArtifactPriority(path: string, priority: number): Promise<void>;

// UI-009
export function SelectDirectory(): Promise<string>;
export function OpenProject(path: string): Promise<ProjectMeta>;
export function CloseProject(idx: number): Promise<void>;
export function SwitchProject(idx: number): Promise<void>;
export function ListOpenedProjects(): Promise<ProjectMeta[]>;
export function ReorderProjects(order: number[]): Promise<void>;
export function LoadRegistry(): Promise<ProjectsRegistry>;
export function ListRecentProjects(): Promise<ProjectMeta[]>;
export function InitializeYukki(dir: string): Promise<void>;

// UI-010
export function WriteArtifact(path: string, content: string): Promise<void>;

// CORE-007 — draft persistence
export function DraftSave(draft: Record<string, unknown>): Promise<void>;
export function DraftLoad(id: string): Promise<Record<string, unknown>>;
export function DraftList(): Promise<DraftSummary[]>;
export function DraftDelete(id: string): Promise<void>;
export function StoryValidate(draft: Record<string, unknown>): Promise<ValidationReport>;

// CORE-009 — story export
export function StoryExport(draft: Record<string, unknown>, options: ExportOptions): Promise<ExportResult>;

// CORE-008 — LLM suggestion streaming
export function SpddSuggestStart(req: SuggestionRequest): Promise<string>;
export function SpddSuggestCancel(sessionID: string): Promise<void>;
export function SpddSuggestPreview(req: SuggestionRequest): Promise<string>;

// UI-015 — PDF export
export function SaveFilePdf(suggestedName: string): Promise<string>;
export function WritePdfFile(path: string, base64Content: string): Promise<void>;
export function ResolveCanvasChain(canvasPath: string): Promise<CanvasChain>;

export interface CanvasChain {
  StoryPath: string;
  AnalysisPath: string;
  CanvasPath: string;
}

// UI-021 — About dialog
export function GetBuildInfo(): Promise<BuildInfo>;

export interface BuildInfo {
  Version: string;
  CommitSHA: string;
  BuildDate: string;
}

// OPS-001 — settings + logging
export function LoadSettings(): Promise<Settings>;
export function SaveSettings(settings: Settings): Promise<void>;
export function LogToBackend(payload: LogPayload): Promise<void>;
export function OpenLogsFolder(): Promise<void>;

// OPS-001 prompt-update — build-time gating + logs drawer
export function IsDevBuild(): Promise<boolean>;
export function TailLogs(maxLines: number): Promise<LogLine[]>;

export interface Settings {
  DebugMode: boolean;
}

export interface LogPayload {
  Level: string;
  Source: string;
  Msg: string;
  Stack: string;
}

export interface LogLine {
  Timestamp: string;
  Level: string;
  Source: string;
  Msg: string;
  Raw: string;
}

export interface DraftSummary {
  id: string;
  title: string;
  updatedAt: string;
}

export interface FieldError {
  field: string;
  severity: string;
  message: string;
}

export interface ValidationReport {
  errors: FieldError[];
}

export interface ExportOptions {
  Overwrite: boolean;
}

export interface ExportResult {
  path: string;
  bytes: number;
  writtenAt: string;
}

export interface SuggestionRequest {
  section: string;
  action: string;
  selectedText: string;
  previousSuggestion: string;
}

export interface ProjectMeta {
  Path: string;
  Name: string;
  LastOpened: string;
}

export interface ProjectsRegistry {
  version: number;
  active_index: number;
  opened_projects: Array<{ path: string; name: string; last_opened: string }>;
  recent_projects: Array<{ path: string; name: string; last_opened: string }>;
}

export interface Meta {
  ID: string;
  Slug: string;
  Title: string;
  Status: string;
  Created?: string;
  Updated: string;
  Priority?: number;
  Path: string;
  Error?: string;
}

export interface ClaudeStatus {
  Available: boolean;
  Version: string;
  Err: string;
}
