// AV-WORKAROUND STUB — normally auto-generated by `wails generate module`.
// Hand-written locally because corporate Defender blocks the helper binary
// Wails builds in %TEMP% during binding generation. Cf. TICKET IT in TODO.md.
// Wails overwrites this file cleanly once the AV exclusion is in place.

// (Greet was removed in UI-001c per D-C11.)
export function SelectProject(): Promise<string>;
export function AllowedKinds(): Promise<string[]>;
export function ListArtifacts(kind: string): Promise<Meta[]>;
export function GetClaudeStatus(): Promise<ClaudeStatus>;
export function InitializeSPDD(dir: string): Promise<void>;
export function ReadArtifact(path: string): Promise<string>;

// UI-001c
export function RunStory(description: string, prefix: string, strictPrefix: boolean): Promise<string>;
export function AbortRunning(): Promise<void>;
export function SuggestedPrefixes(): Promise<string[]>;

export interface Meta {
  ID: string;
  Slug: string;
  Title: string;
  Status: string;
  Updated: string;
  Path: string;
  Error?: string;
}

export interface ClaudeStatus {
  Available: boolean;
  Version: string;
  Err: string;
}
